### ISSUE TITLE
Create GitHub issues interation module for SOWNBot

### ISSUE THREAD

**Issue by drn05r** [sown/tasks#13]
**This should be transferred as an issue for the SOWNBot repo once created.**

If we are going to use GitHub issues it would be useful to have a replacement for the SOWNBot TodoModule.java that allows issues to be created, edited, commented on and resolved from IRC.

**Comment by TimStallard** [comment]
[irccat](https://github.com/irccloud/irccat.git) has excellent support for processing github webhooks and dumping a little message to IRC - that'd get any comments on issues, code pushed, etc nicely logged to IRC. I've seen it used in a few public channels and it seems to work nicely.

It might be possible to hack it up to send over TCP to sown-bot rather than directly to IRC itself?

**Comment by TimStallard** [comment]
https://github.com/xPaw/GitHub-WebHook looks far more suitable for this - and the example was easy enough to modify to talk to SOWN-Bot and add !h for anything from private repos.

Got it working on my own webserver for now, need to look at somewhere sensible to deploy it (www?) tomorrow.

**Comment by TimStallard** [comment]
Webhook handler set up, seems to work OK. I think this covers a lot of the functionality here, and avoids any complicated handling of confusing IRC users and bots etc if actually editing issues via IRC, so closing for now.
