### ISSUE TITLE
Fix RADIUS authentication to replaced Jisc roaming servers (part 2)

### ISSUE THREAD

**Issue by spaetow** [sown/tasks#84]
Please update your configuration to send traffic to the new roaming1.ja.net (IPv4: 193.63.195.34, IPv6: 2001:630:1:132::34). Same thing as #79, server was replaced and no traffic is currently seen on it from any SOWN servers.

**Comment by drn05r** [comment]
Hi Stefan,

I updated FreeRadius configuration back on 13th June.  (Later than I had planned because I forgot that my centralised update would not actually roll out a config changed to the RADIUS server). However, what I have failed to do was reconfigure the routing on this RADIUS server to route traffic via the correct interface if it was going to one of the roaming servers on ja.net.

I just ran an eapol_check to specifically use roaming1 and this looks to have worked.  I have only had two authentications since this routing update, which look to have gone to roaming0 and roaming2, so I have restarted freeradius in case that is needed to pick up the new routing.  Just now I can see on newsupport.eduoam.uk that there has been a genuine an successful authentication to roaming1.

Regards

David Newman
