### ISSUE TITLE
Import Ansible SOWN Git repository to GitHub

### ISSUE THREAD

**Issue by drn05r** [sown/tasks#9]

**Comment by drn05r** [comment]
Need to check there is no private information in this before doing so.

**Comment by drn05r** [comment]
Hi Tim,

As @TimStallard has already imported this as a private repo I thought I would assign it to you as well.  I am happy to check over stuff.  I guess what we should do is not commit the Ansible hosts file.  I don't think this is a problem historically but for ease of reuse if we make public this file should not be present.  Maybe we should have a placeholder hosts.tmpl.

**Comment by TimStallard** [comment]
If we're attempting to make the repository more generic, it might also be nice to remove the use of /etc/ansible in lots of playbooks, and use relative paths instead. That way multiple people could have their own checkouts of the repo on auth2 (or wherever), and work on playbooks individually.

For my personal infrastructure, I structure this with files stored alongside the playbooks, rather than in their own separate files directory tree - it might make sense to do this for sown, or maybe even restructure it completely into roles? Otherwise we could probably just do `../../../files/playbook/foo.bar` or whatever, and stick with the current directory structure.

**Comment by TimStallard** [comment]
We've been working on a new ansible repo to be public, so the old one can stay private for now. So this can be closed.
